##################################
#Triggered on push to main. 
#Builds image, pushes to ECR, updates the Helm chart values.yaml (image.tag) in the repo and commits the change. 
#ArgoCD watches the repo and will sync to EKS automatically (GitOps).
####################################


name: Prod — Main → Build → Update Helm → ArgoCD

on:
  push:
    branches:
      - "main"

env:
  REGION: ap-southeast-1
  IMAGE: ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPO }}

jobs:
  build-and-update-helm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: aws-actions/amazon-ecr-login@v2

      - name: Build + push ECR image
        uses: docker/build-push-action@v4
        with:
          context: ./go-app
          push: true
          tags: |
            ${{ env.IMAGE }}:prod-${{ github.sha }}
            ${{ env.IMAGE }}:latest

      - name: Install yq
        run: sudo snap install yq

      - name: Update Helm image.tag
        run: |
          cd helm/stark-industries-go
          yq eval -i ".image.tag = \"prod-${GITHUB_SHA}\"" values.yaml
          git config user.email "${{ secrets.USER_EMAIL }}"
          git config user.name "${{ secrets.USER_NAME }}"
          git add values.yaml
          git commit -m "chore: update image tag to prod-${GITHUB_SHA}" || echo "No change"
          git push
