apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: stark-industries-go-vs
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/istio-ingressgateway
  http:
  - route:
    - destination:
        host: stark-industries-go-service
        subset: v1
      weight: 50
    - destination:
        host: stark-industries-go-service
        subset: v2
      weight: 50
